### PR TITLE
Add forest carbon diligence scripts

### PR DESCRIPTION
**Pull request by thomas-maschler**
This PR includes 3 eval scripts for the Forest Carbon Diligence data product for visualizing
- Aboveground Carbon Density
- Canopy Height
- Canopy Cover

### CODE REVIEW

**Comment by jonasViehweger** [comment]
Thanks for the PR. If alright with you I'd do two changes:

For all scripts I would also add a tab with an evalscript which outputs the raw values and one which is compatible with EO Browser. Like on this page for example: https://custom-scripts.sentinel-hub.com/sentinel-2/ndmi/

There's also the parent page (`planetary-variables`) for `forest-carbon-diligence` missing. In its purest form it would just look like this page: https://custom-scripts.sentinel-hub.com/copernicus_services/ However if you want to add any text to explain the different PVs that would also be possible. To keep root a bit less bloated, I would move the folder you added to `planetary-variables > forest-carbon-diligence`

**Comment by thomas-maschler** [comment]
Sounds good. Thanks for the updates. I have no preference on where this should live. PVs felt natural to me, as this is a L4 product and very different from PlanetScope data. @cpaulik, where did you plan to store your PVs?

**Comment by cpaulik** [comment]
I think a Planetary Variables folder makes a lot of sense. We'll add the other PVs there as well.

**Comment by jonasViehweger** [comment]
Perfect, then no other changes are necessary

**Pull request merged**
