### PR TITLE
Update global mosaic script

### PR DESCRIPTION
**Pull request by mlubej**
Implementation of changes to the script so that it is in line with what is available and presented on https://collections.sentinel-hub.com/sentinel-s2-l2a-mosaic-120/

### CODE REVIEW

**Comment by mlubej** [comment]
@maximlamare @Kampen1988 @Dorothyrono I'm not sure who reviews or manages this repo. I'm tagging you just in case, otherwise there is not much to review.

**Comment by Dorothyrono** [comment]
tagging you  @MonjaSebela , I think you  are the right person to review

**Comment by MonjaSebela** [comment]
A couple of comments: 
- It seems that the "world" image wasn't uploaded, and so it doesn't show
- Is it possible to show this script in EO Browser? If so, the chapter "Evaluate and Visualize" with a link should be added. If the script is too long, that function where it reads the .js file directly can be used. 
- At the top of the README file, the code that toggles script should be added, unless there's a reason not to:

```javascript
<a href="#" id='togglescript'>Show</a> script or [download](script.js){:target="_blank"} it.
<div id='script_view' style="display:none">
{% highlight javascript %}
      {% include_relative script.js %}
{% endhighlight %}
</div>
```

**Comment by mlubej** [comment]
Thanks @MonjaSebela !


>     * It seems that the "world" image wasn't uploaded, and so it doesn't show

fixed, forgot to add it

>     * Is it possible to show this script in EO Browser? If so, the chapter "Evaluate and Visualize" with a link should be added. If the script is too long, the option where it reads the .js file directly can be used.

I don't think so, it returns a multi-temporal tiff and it is probably too heavy to use it via EO Browser.

 
>     * At the top of the README file, the code that toggles script should be added, unless there's a reason not to:

added, but changed a bit:

```html
<a href="#" id='togglescript'>Show</a> script or <a href="/custom-scripts/sentinel-2/interpolated_time_series/script.js" target="_blank">download</a> it.
<div id='script_view' style="display:none">
   {% highlight javascript %}
   {% include_relative script.js %}
   {% endhighlight %}
</div>
```

**Pull request merged**
