### PR TITLE
Fire Boundary Script from the SH Custom Script Contest

### PR DESCRIPTION
**Pull request by sabinadolenc**

### CODE REVIEW

**Comment by gmilcinski** [comment]
Some comments:  
README.md  
-if you compare to one exemplary script (https://raw.githubusercontent.com/sentinel-hub/custom-scripts/master/sentinel-2/ndwi/README.md) you will notice:  
--the title of the script is header 1 (#) not header 2 (##)  
--the rest of the headers should probably be ## not ###
--Evaluate and visualize part is missing  
--the header title "General description of the script" is missing (the content is there)

-Please make these as consistent as possible

script.js  
I think we can avoid the description of what script does in the script as README.md is there for this purpose. You can/should leave the authors there though.  
Also remove the "award" part

**Comment by gmilcinski** [comment]
Sabina, make sure you also update the "IO" part of the custom script package, so that scripts are shown here:  
https://sentinel-hub.github.io/custom-scripts/
@batic can tell you, what needs to be done.

**Comment by batic** [comment]
> https://sentinel-hub.github.io/custom-scripts/ <https://sentinel-hub.github.io/custom-scripts/>
> 
This page is automatically generated from Readme files in the repository, there is nothing to be done.  custom-scripts.sentinelhub.com <http://custom-scripts.sentinelhub.com/> is then a link to the page above.

I don’t know how much you’d want to promote these scripts, but one suggestion is that the main Readme has additional section “Custom script contest, 2019” and there a short paragraph about the contest and a list (with links) to scripts, similarly like we have Sentinel-2  > Popular RGB composites.

Let me know if you have questions.

**Comment by gmilcinski** [comment]
Then this "automatic generation" needs to be run as the Fire boundary script is not visible on https://custom-scripts.sentinel-hub.com/ ...  

I do not think we want to showcase the contest itself in any special way. We just want to make sure that these scripts are visible in all the places, where we show the scripts (not just in GitHub)

**Comment by batic** [comment]
What do you mean that they are not visible?
https://custom-scripts.sentinel-hub.com/sentinel-2/fire_boundary/ <https://custom-scripts.sentinel-hub.com/sentinel-2/fire_boundary/>
https://sentinel-hub.github.io/custom-scripts/sentinel-2/fire_boundary/ <https://sentinel-hub.github.io/custom-scripts/sentinel-2/fire_boundary/> 

What is not automatically generated is the Readme file in the main folder of the repo. There the link to the script should be added.

**Comment by gmilcinski** [comment]
What I meant is that if you do not know this URL (and I do not know, how one could know), there is no way to get to it. And neither the Google can get to it, I think.

So we need to add it to the Readme file in the main folder repo

**Comment by batic** [comment]
> What I meant is that if you do not know this URL (and I do not know, how one could know), there is no way to get to it. And neither the Google can get to it, I think.
> 
> So we need to add it to the Readme file in the main folder repo
> 
Yes. Link has to be manually added to Readme in main repo folder.

**Comment by sabinadolenc** [comment]
I've uploaded all the scripts from the contest and updated the Readme in the main repo accordingly.  Not to mention the contest I used the categories to systematically organize the scripts.

To the Readme in the main repo, I've also added the missing information from other data sources already existing in the repo: https://sentinel-hub.github.io/custom-scripts/

Please let me know if you notice any inconsistencies.

**Pull request merged**
